name: test-actions
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NO_COVERAGE_BADGE_UPDATE: 1
      PROMPT_NAME: test name
      PROMPT_EMAIL: test+email@example.com
    steps:
      - run: uname -a
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "v1.x"
      - uses: antongolub/action-setup-bun@v1
      - run: |
          yarn install
          bun install
      - run: yarn build
      # yarn coverage === c8 + yarn test:node
      - run: yarn coverage
      - run: yarn test:deno
      - run: yarn test:bun
        continue-on-error: true
        env:
          BUN_IN_MEMORY_FETCH: true
      - name: test:node with PORT
        run: yarn test:node
        env:
          PORT: 3400
      - name: test:deno with PORT
        run: yarn test:deno
        env:
          PORT: 3400
      - name: test:bun with PORT
        run: yarn test:bun
        continue-on-error: true
        env:
          PORT: 3400
          BUN_IN_MEMORY_FETCH: true
